name: Pipeline CI/CD pour site statique

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
    # Job 1: Build
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build the static site
              run: 
                echo "Le site statique est prêt à être testé." 
                # Possible d'ajouter une étape de compilation pour un framwork front-end

    # Job 2: Test
    test:
        runs-on: ubuntu-latest
        needs: build # Ce job ne se lance que si le job 'build' a réussi
        steps:
            - uses: actions/checkout@v3
            - name: Lancement des tests de validation
              run: 
                echo "Lancement des tests... Les tests ont réussi avec succès !"

    # Job 3: Déploiement
    deploy:
        runs-on: ubuntu-latest
        needs: test # Ce job ne se lance que si le job 'test' a réussi
        if: github.ref == 'refs/heads/master' 
            # Déploiement uniquement depuis la branche 'master'
        steps:
            - uses: actions/checkout@v3
            - name: Déploiement sur GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./ # Le dossier à déployer
